version: '3.8'

services:
  infractions-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add your infractions API service here
  # infractions-api:
  #   image: your-api-image:latest
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped

networks:
  default:
    name: infractions-network
